name: SonarCloud Analysis
description: Run SonarCloud scan, print Quality Gate and New Code Coverage

inputs:
  project_key:
    required: true
  organization:
    required: true
  sonar_token:
    required: true
  github_token:
    required: true

runs:
  using: composite
  steps:
    - name: Run SonarCloud Scan
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        mvn -B verify sonar:sonar \
          -Dsonar.projectKey=${{ inputs.project_key }} \
          -Dsonar.organization=${{ inputs.organization }} \
          -Dsonar.host.url=https://sonarcloud.io

    - name: Print Quality Gate & New Code Coverage
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
      run: |
        PROJECT_KEY="${{ inputs.project_key }}"
        SONAR_API="https://sonarcloud.io/api"

        echo "Fetching Quality Gate status..."
        QG_STATUS=$(curl -s -u ${{ env.SONAR_TOKEN }}: \
          "$SONAR_API/qualitygates/project_status?projectKey=$PROJECT_KEY" \
          | jq -r '.projectStatus.status')

        COVERAGE=$(curl -s -u ${{ env.SONAR_TOKEN }}: \
          "$SONAR_API/measures/component?component=$PROJECT_KEY&metricKeys=coverage" \
          | jq -r '.component.measures[0].value')

        echo ""
        echo "Quality Gate: $QG_STATUS"
        echo "Coverage: $COVERAGE% (threshold 80%)"

    - name: Check scannerwork folder
      shell: bash
      run: ls -la .scannerwork/

    - name: SonarCloud Quality Gate
      uses: sonarsource/sonarqube-quality-gate-action@v1
      with:
        scanMetadataReportFile: .scannerwork/report-task.txt
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
